version: '3.9'
services:
  toolmanager:
    image: ghcr.io/<your-username>/<your-repository>:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cobalt-api:
    image: ghcr.io/imputnet/cobalt:latest
    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt-api
    environment:
      - API_URL="https://homer-cygqfaaahphscydj.westeurope-01.azurewebsites.net/"
    ports:
      - "1111:1111"
